Repository irismehanovic/animal-renting-backend, pull requests merged in 2022-05, with the labels that each got.

#3 adding dependencies and connecting frontend with backend
  pom.xml
  src/main/java/com/animalrenting/controllers/AnimalController.java
  src/main/java/com/animalrenting/controllers/AnimalList.java
  src/main/java/com/animalrenting/models/Animal.java
  src/main/java/com/animalrenting/models/Animals.java
  src/main/java/com/animalrenting/repositories/AnimalRepository.java
  src/main/java/com/animalrenting/services/AnimalServices.java
  src/main/java/com/animalrenting/services/AnimalsServices.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: homework-5

#4 Adding user backend postgreSQL
  src/main/java/com/animalrenting/models/Users.java
  src/main/java/com/animalrenting/repositories/UsersRepository.java
  src/main/java/com/animalrenting/services/UserServices.java
Labels: homework-5

#5 Further backend develop
  .DS_Store
  .gitignore
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/animalrenting/config/CorsConfiguration.java
  src/main/java/com/animalrenting/models/Animal.java
  src/main/java/com/animalrenting/models/Owner.java
  src/main/java/com/animalrenting/repositories/AnimalRepository.java
  src/main/java/com/animalrenting/services/AnimalServices.java
  src/main/resources/application.yml
  system.properties.properties
Labels: homework-6

#8 Adding getByCity method
  src/main/java/com/animalrenting/models/Users.java
  src/main/java/com/animalrenting/repositories/UsersRepository.java
  src/main/java/com/animalrenting/services/UserServices.java
  src/test/java/com/animalrenting/services/UserServiceTest.java
Labels: homework-8
